In [91]:
import pandas as pd

In [92]:
df = pd.read_csv("data/interim.csv")
data_dict = pd.read_csv("data/answers-data-dictionary-0.2.0-domains.csv", sep=";")

In [93]:
df.isna().sum()[df.isna().sum() > 0].sort_values(ascending=True)

education             1
psqi_4               20
age                  26
msfsc2              396
mh_meds_1_name      735
mh_meds_1_dose      735
mh_meds_1_timing    735
mh_meds_1_reason    735
mh_meds_2           735
mh_meds_2_name      866
mh_meds_2_dose      866
mh_meds_2_timing    866
mh_meds_2_reason    866
mh_meds_3           866
mh_meds_3_name      932
mh_meds_3_timing    932
mh_meds_4           932
mh_meds_3_reason    932
mh_meds_3_dose      933
mh_meds_4_name      952
mh_meds_4_dose      952
mh_meds_4_timing    952
mh_meds_4_reason    952
mh_meds_5           952
mh_meds_5_name      961
mh_meds_5_dose      961
mh_meds_5_timing    961
mh_meds_5_reason    961
mh_meds_6           961
mh_meds_6_name      967
mh_meds_6_dose      967
mh_meds_6_timing    967
mh_meds_6_reason    967
dtype: int64

In [94]:
df = df.drop(["id", "visit", "msfsc2"], axis=1)
df.dropna(subset=["education", "age"], inplace=True)

In [95]:
df.isna().sum()[df.isna().sum() > 0].sort_values(ascending=True)

psqi_4               20
mh_meds_1_name      712
mh_meds_1_dose      712
mh_meds_1_timing    712
mh_meds_1_reason    712
mh_meds_2           712
mh_meds_2_name      840
mh_meds_2_dose      840
mh_meds_2_timing    840
mh_meds_2_reason    840
mh_meds_3           840
mh_meds_3_name      905
mh_meds_3_timing    905
mh_meds_3_reason    905
mh_meds_4           905
mh_meds_3_dose      906
mh_meds_4_name      925
mh_meds_4_dose      925
mh_meds_4_timing    925
mh_meds_4_reason    925
mh_meds_5           925
mh_meds_5_name      934
mh_meds_5_dose      934
mh_meds_5_timing    934
mh_meds_5_reason    934
mh_meds_6           934
mh_meds_6_name      940
mh_meds_6_dose      940
mh_meds_6_timing    940
mh_meds_6_reason    940
dtype: int64

In [96]:
cols_for_total_score = [col for col in df.columns if "total" in col]
cols_for_total_score

['psqi_total',
 'brisc_total',
 'isi_total',
 'upps_total',
 'cesd_total',
 'gad_total',
 'ddnsi_total']

In [97]:
cols_lifestyle = ["subs_alc_1", "subs_tob_1", "subs_can_1"]

In [98]:
cols_sleep = ["socialjetlag", "msfsc1"]

In [99]:
cols_medical_history = data_dict[(data_dict['folder'].str.contains("Medical History")) & (data_dict['folder'].str.contains("Medications") == False)].id.to_list()
cols_medical_history

['mh_anx', 'mh_bpd', 'mh_health', 'mh_mdd', 'mh_ptsd', 'mh_pzd', 'mh_szd']

In [100]:
demographic_cols = data_dict[(data_dict['folder'].str.contains("Demographics")) & (data_dict['id'].str.contains("nsrr") == False)].id.to_list() + ["handedness"]
demographic_cols

['education',
 'income',
 'age',
 'ethnicity',
 'orientation',
 'race',
 'sex',
 'transgender',
 'handedness']

In [101]:
# df[cols_for_total_score]
df[cols_lifestyle]
df[cols_sleep]
df[cols_medical_history]

,mh_anx,mh_bpd,mh_health,mh_mdd,mh_ptsd,mh_pzd,mh_szd
0,Yes but undiagnosed,No,Good,Yes but undiagnosed,No,No,No
1,Yes diagnosed by clinician,No,Fair,Yes diagnosed by clinician,Yes but undiagnosed,No,No
2,Yes diagnosed by clinician,Yes diagnosed by clinician,Very Good,Yes diagnosed by clinician,Yes diagnosed by clinician,No,No
3,Yes diagnosed by clinician,No,Excellent,Yes diagnosed by clinician,Yes diagnosed by clinician,No,No
4,Yes but undiagnosed,Not sure,Fair,Not sure,Yes but undiagnosed,No,No
...,...,...,...,...,...,...,...
966,No,No,Very Good,Not sure,No,No,No
967,Yes diagnosed by clinician,No,Good,Yes diagnosed by clinician,No,No,No
968,Yes diagnosed by clinician,No,Fair,No,No,No,No
969,No,No,Very Good,No,No,No,No
970,No,No,Very Good,No,No,No,No

In [102]:
selected_cols = cols_lifestyle + cols_sleep + cols_medical_history + demographic_cols
selected_df = df[selected_cols]

In [103]:
selected_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 944 entries, 0 to 970
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   subs_alc_1    944 non-null    object
 1   subs_tob_1    944 non-null    object
 2   subs_can_1    944 non-null    object
 3   socialjetlag  944 non-null    float64
 4   msfsc1        944 non-null    float64
 5   mh_anx        944 non-null    object
 6   mh_bpd        944 non-null    object
 7   mh_health     944 non-null    object
 8   mh_mdd        944 non-null    object
 9   mh_ptsd       944 non-null    object
 10  mh_pzd        944 non-null    object
 11  mh_szd        944 non-null    object
 12  education     944 non-null    object
 13  income        944 non-null    object
 14  age           944 non-null    float64
 15  ethnicity     944 non-null    object
 16  orientation   944 non-null    object
 17  race          944 non-null    object
 18  sex           944 non-null    object
 19  transgender   944 non-null    object
 20  handedness    944 non-null    object
dtypes: float64(3), object(18)
memory usage: 162.2+ KB

In [104]:
for column in selected_df.columns:
    if selected_df[column].dtype == "object":
        print(column, selected_df[column].unique())

subs_alc_1 ['Once a month or less' 'A few times a week' 'Once a week or less' 'Never'
 'Daily' 'Multiple times daily']
subs_tob_1 ['Never Smoker' 'Daily Smoker' 'Former Smoker' 'Occasional Smoker']
subs_can_1 ['Never' 'Multiple times daily' 'Daily' 'Once a month or less'
 'Once a week or less' 'A few times a week']
mh_anx ['Yes but undiagnosed' 'Yes diagnosed by clinician' 'No' 'Not sure']
mh_bpd ['No' 'Yes diagnosed by clinician' 'Not sure' 'Yes but undiagnosed']
mh_health ['Good' 'Fair' 'Very Good' 'Excellent' 'Poor']
mh_mdd ['Yes but undiagnosed' 'Yes diagnosed by clinician' 'Not sure' 'No']
mh_ptsd ['No' 'Yes but undiagnosed' 'Yes diagnosed by clinician' 'Not sure']
mh_pzd ['No' 'Not sure' 'Yes diagnosed by clinician' 'Yes but undiagnosed']
mh_szd ['No' 'Yes but undiagnosed' 'Not sure' 'Yes diagnosed by clinician']
education ['High school or less' 'College or more']
income ['$25,000 - $50,000' 'Prefer not to say' '< $25,000' '$50,000 - $100,000'
 '$100,000 - $200,000' '>$200,000']
ethnicity ['Non-Hispanic' 'Hispanic']
orientation ['Heterosexual' 'Bisexual' 'Homosexual' 'Other']
race ['White' 'Multiracial' 'Asian' 'Native' 'Black' 'Islander']
sex ['Female' 'Male']
transgender ['No' 'Yes']
handedness ['Right' 'Left' 'Both']

In [ ]:
subs_alc_1_map = {
    'Never': 0,
    'Once a month or less': 1,
    'Once a week or less': 2,
    'A few times a week': 3,
    'Daily': 4,
    'Multiple times daily': 5
}

subs_tob_1_map = {
    'Never Smoker': 0,
    'Former Smoker': 1,
    'Occasional Smoker': 2,
    'Daily Smoker': 3
}

subs_can_1_map = {
    'Never': 0,
    'Once a month or less': 1,
    'Once a week or less': 2,
    'A few times a week': 3,
    'Daily': 4,
    'Multiple times daily': 5
}

mh_anx_map = {
    'Not sure': -1,
    'No': 0,
    'Yes but undiagnosed': 1,
    'Yes diagnosed by clinician': 2
}

mh_bpd_map = {
    'Not sure': -1,
    'No': 0,
    'Yes but undiagnosed': 1,
    'Yes diagnosed by clinician': 2
}

mh_health_map = {
    'Poor': 0,
    'Fair': 1,
    'Good': 2,
    'Very Good': 3,
    'Excellent': 4
}

mh_mdd_map = {
    'Not sure': -1,
    'No': 0,
    'Yes but undiagnosed': 1,
    'Yes diagnosed by clinician': 2
}

mh_ptsd_map = {
    'Not sure': -1,
    'No': 0,
    'Yes but undiagnosed': 1,
    'Yes diagnosed by clinician': 2
}

mh_pzd_map = {
    'Not sure': -1,
    'No': 0,
    'Yes but undiagnosed': 1,
    'Yes diagnosed by clinician': 2
}

mh_szd_map = {
    'Not sure': -1,
    'No': 0,
    'Yes but undiagnosed': 1,
    'Yes diagnosed by clinician': 2
}

education_map = {
    "High school or less": 0,
    "College or more": 1
}

income_map = {
    "< $25,000": 0,
    "$25,000 - $50,000": 1,
    "$50,000 - $100,000": 2,
    "$100,000 - $200,000": 3,
    ">$200,000": 4,
    "Prefer not to say": -1
}

ethnicity_map = {
    "Non-Hispanic": 0,
    "Hispanic": 1
}

orientation_map = {
    "Heterosexual": 0,
    "Bisexual": 1,
    "Homosexual": 2,
    "Other": 3
}

race_map = {
    "White": 0,
    "Multiracial": 1,
    "Asian": 2,
    "Native": 3,
    "Black": 4,
    "Islander": 5
}

sex_map = {
    "Female": 0,
    "Male": 1
}

transgender_map = {
    'No': 0,
    'Yes': 1
}

handedness_map = {
    'Right': 0,
    'Left': 1,
    'Both': 2
}

selected_df["subs_alc_1"] = selected_df["subs_alc_1"].map(subs_alc_1_map)
selected_df["subs_tob_1"] = selected_df["subs_tob_1"].map(subs_tob_1_map)
selected_df["subs_can_1"] = selected_df["subs_can_1"].map(subs_can_1_map)
selected_df["mh_anx"] = selected_df["mh_anx"].map(mh_anx_map)
selected_df["mh_bpd"] = selected_df["mh_bpd"].map(mh_bpd_map)
selected_df["mh_health"] = selected_df["mh_health"].map(mh_health_map)
selected_df["mh_mdd"] = selected_df["mh_mdd"].map(mh_mdd_map)
selected_df["mh_ptsd"] = selected_df["mh_ptsd"].map(mh_ptsd_map)
selected_df["mh_pzd"] = selected_df["mh_pzd"].map(mh_pzd_map)
selected_df["mh_szd"] = selected_df["mh_szd"].map(mh_szd_map)
selected_df["education"] = selected_df["education"].map(education_map)
selected_df["income"] = selected_df["income"].map(income_map)
selected_df["ethnicity"] = selected_df["ethnicity"].map(ethnicity_map)
selected_df["orientation"] = selected_df["orientation"].map(orientation_map)
selected_df["race"] = selected_df["race"].map(race_map)
selected_df["sex"] = selected_df["sex"].map(sex_map)
selected_df["transgender"] = selected_df["transgender"].map(transgender_map)
selected_df["handedness"] = selected_df["handedness"].map(handedness_map)

C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:127: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["subs_alc_1"] = selected_df["subs_alc_1"].map(subs_alc_1_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:128: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["subs_tob_1"] = selected_df["subs_tob_1"].map(subs_tob_1_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:129: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["subs_can_1"] = selected_df["subs_can_1"].map(subs_can_1_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["mh_anx"] = selected_df["mh_anx"].map(mh_anx_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:131: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["mh_bpd"] = selected_df["mh_bpd"].map(mh_bpd_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["mh_health"] = selected_df["mh_health"].map(mh_health_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["mh_mdd"] = selected_df["mh_mdd"].map(mh_mdd_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:134: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["mh_ptsd"] = selected_df["mh_ptsd"].map(mh_ptsd_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:135: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["mh_pzd"] = selected_df["mh_pzd"].map(mh_pzd_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:136: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["mh_szd"] = selected_df["mh_szd"].map(mh_szd_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["education"] = selected_df["education"].map(education_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:138: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["income"] = selected_df["income"].map(income_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:139: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["ethnicity"] = selected_df["ethnicity"].map(ethnicity_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:140: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["orientation"] = selected_df["orientation"].map(orientation_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:141: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["race"] = selected_df["race"].map(race_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:142: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["sex"] = selected_df["sex"].map(sex_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:143: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["transgender"] = selected_df["transgender"].map(transgender_map)
C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1675831158.py:144: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["handedness"] = selected_df["handedness"].map(handedness_map)

In [108]:
selected_df.drop(["mh_szd", "mh_pzd", "mh_ptsd", "mh_bpd", "handedness", "ethnicity", "subs_can_1"], axis=1, inplace=True)

C:\Users\Jan\AppData\Local\Temp\ipykernel_12428\1268819617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df.drop(["mh_szd", "mh_pzd", "mh_ptsd", "mh_bpd", "handedness", "ethnicity", "subs_can_1"], axis=1, inplace=True)

In [109]:
selected_df

,subs_alc_1,subs_tob_1,socialjetlag,msfsc1,mh_anx,mh_health,mh_mdd,education,income,age,orientation,race,sex,transgender
0,1,0,-32.4,1.375000,1,2,1,0,1,18.75,0,0,0,0
1,3,3,67.5,1.197917,2,1,2,0,-1,19.74,1,1,0,0
2,2,3,60.0,1.152083,2,3,2,0,0,27.33,1,0,0,0
3,2,3,60.0,1.000000,2,4,2,1,-1,29.60,0,0,0,0
4,2,0,342.5,1.240575,1,1,-1,0,2,26.71,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,0,0,90.0,0.979167,0,3,-1,0,0,19.15,0,2,0,0
967,2,0,45.0,1.122272,2,2,2,0,0,22.07,0,0,0,0
968,1,0,-30.0,1.113095,2,1,0,0,0,19.62,0,0,0,0
969,4,2,-97.5,1.170387,0,3,0,0,3,19.50,0,4,0,1
970,2,1,122.5,1.381944,0,3,0,0,0,21.84,0,1,1,0

In [110]:
selected_df.to_csv("data/selected_cols.csv", index=False)